//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.tnLabs.Core.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tnLabsDBEntities : DbContext
    {
        public tnLabsDBEntities()
            : base("name=tnLabsDBEntitiesOld")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SessionUser> SessionUsers { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<VirtualMachine> VirtualMachines { get; set; }
        public DbSet<Identity> Identities { get; set; }
        public DbSet<SubscriptionIdentityRole> SubscriptionIdentityRoles { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
        public DbSet<Lab> Labs { get; set; }
        public DbSet<RecommendedVMImage> RecommendedVMImages { get; set; }
        public DbSet<TemplateVM> TemplateVMs { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<HealthCheck> HealthChecks { get; set; }
    }
}
