//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.tnLabs.Core.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab
    {
        public Lab()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public int LabId { get; set; }
        public string Name { get; set; }
        public string ImageName { get; set; }
        public string Description { get; set; }
        public int SubscriptionId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool Removed { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
