//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.tnLabs.Core.Repository
{
	
	using System;
	using System.Collections.Generic;
  
    public partial class Session
    {
        public Session()
        {
            this.SessionUsers = new HashSet<SessionUser>();
            this.VirtualMachines = new HashSet<VirtualMachine>();
        }
    
        public int SessionId { get; set; }
        public string SessionName { get; set; }
        public int LabId { get; set; }
        public System.DateTimeOffset StartDate { get; set; }
        public System.DateTimeOffset EndDate { get; set; }
        public Nullable<System.TimeSpan> StartInterval { get; set; }
        public Nullable<System.TimeSpan> EndInterval { get; set; }
        public int SchedulingType { get; set; }
        public string VmSize { get; set; }
        public int SubscriptionId { get; set; }
        public bool Removed { get; set; }
        public string Version { get; set; }
    
        public virtual Lab Lab { get; set; }
        public virtual ICollection<SessionUser> SessionUsers { get; set; }
        public virtual ICollection<VirtualMachine> VirtualMachines { get; set; }
    }
}
