//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.tnLabs.Core.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionIdentityRole
    {
        public int SubscriptionId { get; set; }
        public int IdentityId { get; set; }
        public string Role { get; set; }
    
        public virtual Identity Identity { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
