//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.tnLabs.Core.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.SubscriptionIdentityRoles = new HashSet<SubscriptionIdentityRole>();
            this.Labs = new HashSet<Lab>();
            this.TemplateVMs = new HashSet<TemplateVM>();
            this.Users = new HashSet<User>();
        }
    
        public int SubscriptionId { get; set; }
        public string AzureSubscriptionId { get; set; }
        public string CertificateKey { get; set; }
        public string BlobStorageName { get; set; }
        public string BlobStorageKey { get; set; }
        public byte[] Certificate { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SubscriptionIdentityRole> SubscriptionIdentityRoles { get; set; }
        public virtual ICollection<Lab> Labs { get; set; }
        public virtual ICollection<TemplateVM> TemplateVMs { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
