//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.tnLabs.Core.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateVM
    {
        public int TemplateVMId { get; set; }
        public string ServiceName { get; set; }
        public string VMName { get; set; }
        public int SubscriptionId { get; set; }
        public int CreatorId { get; set; }
        public int State { get; set; }
        public string VMAdminUser { get; set; }
        public string VMAdminPass { get; set; }
        public System.Guid Key { get; set; }
        public string VMLabel { get; set; }
        public string Description { get; set; }
        public int VmRdpPort { get; set; }
        public string ImageName { get; set; }
        public string SourceImageName { get; set; }
        public System.DateTimeOffset StateChangedTimestamp { get; set; }
    
        public virtual Identity Identity { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
