//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.tnLabs.Core.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.SessionUsers = new HashSet<SessionUser>();
            this.VirtualMachines = new HashSet<VirtualMachine>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool Removed { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int SubscriptionId { get; set; }
    
        public virtual ICollection<SessionUser> SessionUsers { get; set; }
        public virtual ICollection<VirtualMachine> VirtualMachines { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
