//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.tnLabs.Core.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualMachine
    {
        public int VirtualMachineId { get; set; }
        public int UserId { get; set; }
        public int SessionId { get; set; }
        public string VmName { get; set; }
        public int VmRdpPort { get; set; }
        public string VmAdminUser { get; set; }
        public string VmAdminPass { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> Stopped1 { get; set; }
        public bool Stopped { get; set; }
    
        public virtual User User { get; set; }
        public virtual Session Session { get; set; }
    }
}
